"use strict";
export const adviceQuotes = [
  "today's forecast: windy with a 100% chance of eating a pulled brisket sandwich.",
  "Weather forecast for tonight: dark. Continued dark overnight, with widely scattered light by morning",
  "Climate is what we expect; weather is what we get.",
  "There is no such thing as bad weather, only inappropriate clothing.",
  "Don’t let the weather ruin your mood. That’s what people are for.",
  "Weather is nature’s way of reminding you who’s in charge.",
  "Cloudy with a strong chance of ‘I told you so’.",
  "Rain is just the sky crying because it saw your search history.",
  "Sun’s out, sarcasm’s out too.",
  "Humidity level: soup.",
  "Wearing three outfits today, because I trust the weather like I trust my Wi-Fi.",
  "It’s not the heat—it’s the humidity complaining about the heat.",
  '"If you don’t like the weather, wait five minutes." — Mark Twain',
  "Forecast: 99% chance of me staying inside.",
  "Snowflakes are just butterflies doing yoga.",
  "Today's vibe: partly cloudy with a chance of coffee.",
  '"Some people feel the rain. Others just get wet." — Bob Marley',
  "I checked the forecast. It said ‘Netflix and snacks’.",
  "Windy outside. Perfect day to fight with an umbrella.",
];
